Repository DeveloperAcademy-POSTECH/2024-MC3-A7-Anigeunde, pull requests merged in 2024-09, with the labels that each got.

#64 [Chore] 연주뷰에 현재 선택된 곡명 추가
  Lvlance/Lvlance/Localizable.xcstrings
  Lvlance/Lvlance/Views/BandSetting/BandSettingView.swift
  Lvlance/Lvlance/Views/BandSetting/SongViewModel.swift
  Lvlance/Lvlance/Views/Playing/DetectSoundsView.swift
  Lvlance/Lvlance/Views/Playing/SetupMonitoredSoundView.swift
Labels: 🪢 Chore

#63 [Chore] 악기편집하기 버튼 수정
  Lvlance/Lvlance/Views/BandSetting/SideBar/InstrumentAdd/InstrumentAddingView.swift
  Lvlance/Lvlance/Views/BandSetting/SideBar/SideBarView.swift
  Lvlance/Lvlance/Views/BandSetting/SongViewModel.swift
Labels: 🐞 Bug & Fix, 🪢 Chore, 🎨 UI

#72 [Feat] 연주뷰 뒤로가기 버튼 추가
  Lvlance/Lvlance.xcodeproj/project.pbxproj
  Lvlance/Lvlance/Localizable.xcstrings
  Lvlance/Lvlance/Views/Playing/DetectSoundsView.swift
  Lvlance/Lvlance/Views/Playing/QuitPopoverView.swift
Labels: 💻 Logic

#73 [Fix] 온보딩뷰 로직 수정
  Lvlance/Lvlance/LvlanceApp.swift
  Lvlance/Lvlance/Views/BandSetting/BandSettingView.swift
  Lvlance/Lvlance/Views/Onboardiing/OnboardingView.swift
Labels: 🐞 Bug & Fix

#75 [Chore] Localizing Update
  Lvlance/Lvlance/Localizable.xcstrings
  Lvlance/Lvlance/Manager/CoreDataManager.swift
Labels: 🪢 Chore

#77 [Release] 앱 카테고리 추가
  Lvlance/Lvlance.xcodeproj/project.pbxproj
Labels: 🐞 Bug & Fix

#80 [Hotfix] microphone key 명시적 추가
  Lvlance/Lvlance/Lvlance.entitlements
Labels: 🐞 Bug & Fix

#82 [Hotfix] 애플 리뷰 수정 요구 사항 반영
  Lvlance/Lvlance.xcodeproj/project.pbxproj
  Lvlance/Lvlance.xcodeproj/xcshareddata/xcschemes/Lvlance.xcscheme
  Lvlance/Lvlance/Localizable.xcstrings
  Lvlance/Lvlance/Manager/AudioManaging/MicrophonePermissionManager.swift
  Lvlance/Lvlance/Views/BandSetting/SideBar/SideBarView.swift
  Lvlance/Lvlance/Views/MicSelect/MicSelectView.swift
Labels: 🐞 Bug & Fix
